Added share task feature
PrachiPotdar23/boilerplate-mern pull request #1
Opened 2024-06-19 14:49 UTC by PrachiPotdar23

**Files Modified**
**_task-controller.ts:_** Implemented the shareTask endpoint handler to allow sharing tasks with other users. Used TaskService.shareTask to perform the sharing operation and handled errors such as PermissionError and TaskNotFoundError.
**_TaskService.ts:_** Updated the shareTask method to include logic for sharing tasks. Converted user IDs to ObjectId type and updated the task document using TaskRepository.findOneAndUpdate.
**_task.spec.ts:_** Added test cases to verify the functionality of the shareTask endpoint. Tests include checking successful sharing, handling non-existent tasks, and permissions errors.
Functionality Added
**Share Task Endpoint (POST /api/tasks/:taskId/share):** Added the ability to share a task with other users. Users can specify a list of user IDs (userIds) in the request body to grant access to the task.

2024-06-20 14:39 UTC, PrachiPotdar23 commented
created share-modal for sharing task and added share button that displays users to share task with.

2024-06-22 11:14 UTC, aniketrathi requested changes

2024-06-22 11:14 UTC, aniketrathi commented on docker-compose.dev.yml
> +version: '3.8'
revert

2024-06-22 11:14 UTC, aniketrathi commented on package.json
> +    "test": "cross-env NODE_ENV=production NODE_CONFIG_ENV=testing mocha --exit -r ts-node/register --project src/apps/backend/tsconfig.json test/**/task.spec.ts",
revert

2024-06-22 11:14 UTC, aniketrathi commented on src/apps/backend/modules/task/internal/store/comment-db.ts
> +  text: string;
text -> comment

2024-06-22 11:14 UTC, aniketrathi commented on src/apps/backend/modules/task/internal/store/comment-db.ts
> +    text: {
comment

2024-06-22 11:14 UTC, aniketrathi commented on src/apps/backend/modules/task/internal/store/comment-db.ts
> +      required: true,
index: true

2024-06-22 11:14 UTC, aniketrathi commented on src/apps/backend/modules/task/internal/store/comment-db.ts
> +      required: true,
index:true

2024-06-22 11:14 UTC, aniketrathi commented on src/apps/backend/modules/task/internal/store/comment-db.ts
> +  task: Types.ObjectId;
add a field `active` to handle the deletion flow of comments.

2024-06-22 11:14 UTC, aniketrathi commented on src/apps/backend/modules/task/internal/store/comment-db.ts
> +);
add a new line

2024-06-22 11:14 UTC, aniketrathi commented on src/apps/backend/modules/task/internal/store/share-task-db.ts
> +    collection: 'shared_tasks',
shared-tasks

2024-06-22 11:14 UTC, aniketrathi commented on src/apps/backend/modules/task/internal/store/share-task-db.ts
> +);
add a new line

2024-06-22 11:14 UTC, aniketrathi commented on src/apps/backend/modules/task/internal/store/share-task-db.ts
> +  },
can we add a combined unique index to the fields `taskId` and `userId`

2024-06-22 11:14 UTC, aniketrathi commented on src/apps/backend/modules/task/internal/store/share-task-repository.ts
> +export default SharedTaskRepository;
add a new line

2024-06-22 11:14 UTC, aniketrathi commented on src/apps/backend/modules/task/internal/store/task-db.ts
> +  shared_with: Types.ObjectId[]; // new field to store IDs of users with whom the task is shared
not required

2024-06-22 11:14 UTC, aniketrathi commented on src/apps/backend/modules/task/internal/store/task-db.ts
> +    shared_with: [{ type: Schema.Types.ObjectId, ref: 'Account' }], // new field
not required as we have a separate schema for the shared tasks

2024-06-22 11:14 UTC, aniketrathi commented on src/apps/backend/modules/task/internal/store/task-db.ts
> +);
add a new line

2024-06-22 11:14 UTC, aniketrathi commented on src/apps/backend/modules/task/internal/task-reader.ts
> +        });
Get shared tasks only with populated task and user field

2024-06-22 11:14 UTC, aniketrathi commented on src/apps/backend/modules/task/rest-api/task-router.ts
> +    router.post('/:id/share', ctrl.shareTask); // Define POST /tasks/:id/share endpoint
we can create a separate module for shared-task just like task and account.
APIs can be
POST /shared-tasks for sharing a task.
GET /shared-tasks to get shared tasks.

2024-06-24 05:24 UTC, PrachiPotdar23 commented
refactored the code according to the comments

2024-06-26 02:49 UTC, PrachiPotdar23 commented
refactored the code and added separate module for share-tasks

2024-06-29 18:27 UTC, PrachiPotdar23 commented
restructured the share-tasks and comment modules following consistent structure.

2024-07-02 16:55 UTC, PrachiPotdar23 commented
implemented share tasks and comment section

2024-07-02 16:56 UTC, PrachiPotdar23 commented
implemented share tasks and comment section

2024-07-04 04:43 UTC, aniketrathi requested changes

2024-07-04 04:43 UTC, aniketrathi commented on package.json
> +    "test": "cross-env NODE_ENV=production NODE_CONFIG_ENV=testing mocha --exit -r ts-node/register --project src/apps/backend/tsconfig.json test/**/.ts",
revert this change

2024-07-04 04:43 UTC, aniketrathi commented on src/apps/backend/modules/share-tasks/internal/share-task-util.ts
> +    sharedTask.task = sharedTaskDb.task.toString();
This will not work when task is a object and same goes for account

2024-07-04 04:43 UTC, aniketrathi commented on src/apps/backend/modules/share-tasks/rest-api/share-task-serializer.ts
> +});
title and description should be part of the task and the username should be part of the account

2024-07-04 04:43 UTC, aniketrathi commented on src/apps/backend/modules/share-tasks/rest-api/share-task-server.ts
> +    server.use('/tasks/shared-tasks', shareRouter.router); // Ensure /api is prefixed
This is not correct
Use `/shared-tasks`

2024-07-04 04:43 UTC, aniketrathi commented on src/apps/backend/modules/share-tasks/types.ts
> +}
title and description should be part of the task and the username should be part of the account

2024-07-04 04:43 UTC, aniketrathi commented on src/apps/backend/modules/comments/internal/comment-writer.ts
> +    return commentDb ? CommentUtil.convertCommentDBToComment(commentDb) : null;
If we don't find commentDb then we should throw error instead of returning null

2024-07-04 04:44 UTC, aniketrathi commented
Add a line at the end of every file

2024-07-09 04:47 UTC, aniketrathi requested changes

2024-07-09 04:47 UTC, aniketrathi commented on package.json
> +    "test": "cross-env NODE_ENV=production NODE_CONFIG_ENV=testing mocha --exit -r ts-node/register --project src/apps/backend/tsconfig.json test/**/.ts",
This is not done

2024-07-09 04:47 UTC, aniketrathi commented on src/apps/backend/modules/share-tasks/internal/share-task-util.ts
> +    sharedTask.task = sharedTaskDb.task.toString();
If it is an ObjectId then we can do toString() else we need to create a separate method to convert populated task db to task

2024-07-09 04:47 UTC, aniketrathi commented on src/apps/backend/modules/share-tasks/rest-api/share-task-server.ts
> +    server.use('/tasks/shared-tasks', shareRouter.router); // Ensure /api is prefixed
Still not done

2024-07-09 04:47 UTC, aniketrathi commented on src/apps/backend/modules/comments/rest-api/comment-router.ts
> +    router.get('/:taskId', ctrl.getComments);
/:taskId is not correct
Use / only

2024-07-09 04:47 UTC, aniketrathi commented on src/apps/backend/modules/comments/internal/comment-util.ts
> +    comment.account = commentDb.account;
Handle both account cases. As account can be objected as well as Object< Account >

2024-07-09 04:47 UTC, aniketrathi commented on src/apps/backend/modules/comments/types.ts
> +  account: any;
Task and account shouldn't be any.

2024-07-09 05:16 UTC, aniketrathi requested changes

2024-07-09 05:16 UTC, aniketrathi commented on src/apps/backend/modules/comments/rest-api/comment-server.ts
> +    server.use('/comments', router.router);
Not correct.
It should be /tasks/:taskId/comments

2024-07-10 04:35 UTC, merged